substitutions:
  name: athom-rgbw-light
  friendly_name: Athom RGBW Light
  light_restore_mode: RESTORE_DEFAULT_OFF

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true

logger:
  level: INFO

api:

ota:
  platform: esphome

wifi:
  ap:

dashboard_import:
  package_import_url: github://dexn/esphome-configs/athom-rgbw-light.yaml@main
  import_full_config: true

packages:
  base_package: github://dexn/esphome-configs/packages/base.yaml@main
  fast_boot_package: github://dexn/esphome-configs/packages/fast_boot_light.yaml@main
  device_package: github://dexn/esphome-configs/devices/athom-rgbw-light.yaml@main
