substitutions:
  name: athom-smart-plug-v3
  friendly_name: Athom Smart Plug V3
  update_interval: 10s
  current_limit : "10"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true

logger:
  level: INFO

api:

ota:
  platform: esphome

wifi:
  ap:

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

dashboard_import:
  package_import_url: github://dexn/esphome-configs/athom-smart-plug-v3.yaml@main
  import_full_config: true

packages:
  base_package: github://dexn/esphome-configs/packages/base.yaml@main
  fast_boot_package: github://dexn/esphome-configs/packages/fast_boot_status.yaml@main
  device_package: github://dexn/esphome-configs/devices/athom-smart-plug-v3.yaml@main
