substitutions:
  name: athom-presence-sensor
  friendly_name: Athom Presence Sensor

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"`
  name_add_mac_suffix: true
  project:
    name: "Athom Technology.Presence Sensor"
    version: "1.0.1"

logger:

api:

ota:
  platform: esphome

wifi:
  ap: {}

improv_serial:

web_server: !remove

dashboard_import:
  package_import_url: github://dexn/esphome-configs/athom-presence-sensor.yaml@main
  import_full_config: true

packages:
  base_package: github://dexn/esphome-configs/packages/base.yaml@main
  fast_boot_package: github://dexn/esphome-configs/packages/fast_boot.yaml@main
  device_package: github://dexn/esphome-configs/devices/athom-presence-sensor.yaml@main
