substitutions:
  name: kogan-panel-heater
  friendly_name: Kogan Panel Heater

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true

logger:
  level: INFO

api:

ota:
  platform: esphome

wifi:
  ap:

dashboard_import:
  package_import_url: github://dexn/esphome-configs/kogan-panel-heater.yaml@main
  import_full_config: true

packages:
  base_package: github://dexn/esphome-configs/packages/base.yaml@main
  fast_boot_package: github://dexn/esphome-configs/packages/fast_boot.yaml@main
  device_package: github://dexn/esphome-configs/devices/kogan-panel-heater.yaml@main
