substitutions:
  name: kogan-bladeless-dc-fan
  friendly_name: Kogan Bladeless DC Fan
  restore_mode: RESTORE_DEFAULT_OFF

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true

logger:
  level: INFO

api:

ota:
  platform: esphome

wifi:
  ap:

dashboard_import:
  package_import_url: github://dexn/esphome-configs/kogan-bladeless-dc-fan.yaml@main
  import_full_config: true

packages:
  base_package: github://dexn/esphome-configs/packages/base.yaml@main
  fast_boot_status_package: github://dexn/esphome-configs/packages/fast_boot_status.yaml@main
  device_package: github://dexn/esphome-configs/devices/kogan-bladeless-dc-fan.yaml@main
