substitutions:
  name: tuya-star-projector
  friendly_name: Tuya Star Projector

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true

logger:
  level: INFO

api:

ota:
  platform: esphome

wifi:
  ap:

dashboard_import:
  package_import_url: github://dexn/esphome-configs/tuya-star-projector.yaml@main
  import_full_config: true

packages:
  base_package: github://dexn/esphome-configs/packages/base.yaml@main
  fast_boot_light_package: github://dexn/esphome-configs/packages/fast_boot_light.yaml@main
  device_package: github://dexn/esphome-configs/devices/tuya-star-projector.yaml@main

web_server: !remove
