esphome:
  min_version: 2024.6.0
  project:
    name: "Athom Technology.RGBW Light Strip Controller"
    version: "1.1.1"

esp8266:
  board: esp8285
  restore_from_flash: true

binary_sensor:
  - platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: true
    name: "Power Button"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - light.toggle: Light
      - timing:
          - ON for at least 4s
        then:
          - button.press: Reset

light:
  - platform: rgbw
    name: "Light"
    id: Light
    red: output_red
    green: output_green
    blue: output_blue
    white: output_white
    color_interlock: true

output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO4

  - platform: esp8266_pwm
    id: output_green
    pin: GPIO12

  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO14

  - platform: esp8266_pwm
    id: output_white
    pin: GPIO13
