esphome:
  min_version: 2024.6.0
  comment: "Kogan SmarterHome RGBW Light Bulb"
  project:
    name: "Kogan SmarterHome.RGBW Light Bulb"
    version: "1.0.0"

esp8266:
  board: esp01_1m
  restore_from_flash: true

light:
  - platform: rgbw
    name: "Light"
    id: Light
    red: output_red
    green: output_green
    blue: output_blue
    white: output_white
    restore_mode: ${restore_mode}
    color_interlock: true

output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO4

  - platform: esp8266_pwm
    id: output_green
    pin: GPIO12

  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO14

  - platform: esp8266_pwm
    id: output_white
    pin: GPIO5
    min_power: 15%
    max_power: 30%
    zero_means_zero: true
