esphome:
  comment: "Kogan SmarterHome Bladeless DC Fan"
  project:
    name: "Kogan SmarterHome.Bladeless DC Fan"
    version: "1.0.0"
  name: kogan-bladeless-dc-fan
  friendly_name: Kogan Bladeless DC Fan

esp8266:
  board: esp01_1m
  restore_from_flash: true

logger:
  baud_rate: 0

uart:
    rx_pin: GPIO3
    tx_pin: GPIO1
    baud_rate: 9600

tuya:

fan:
  - platform: tuya
    name: Fan
    switch_datapoint: 1
    speed_datapoint: 2
    speed_count: 9
    oscillation_datapoint: 8
    restore_mode: ${restore_mode}
