name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-firmware:
    name: Build Firmware
    uses: esphome/workflows/.github/workflows/build.yml@main
    with:
      files: |
        arlec-rgbcct-light.yaml
        athom-presence-sensor.yaml
        athom-rgbw-light.yaml
        athom-smart-plug-v2.yaml
        kogan-bladeless-dc-fan.yaml
        kogan-rgbw-light.yaml
        kogan-smart-power-board.yaml
        mirabella-rgbw-light.yaml
        tuya-star-projector.yaml
      esphome-version: 2024.7.3
      release-summary: ${{ github.event_name == 'release' && github.event.release.body || '' }}
      release-url: ${{ github.event_name == 'release' && github.event.release.html_url || '' }}
      release-version: ${{ github.event_name == 'release' && github.event.release.tag_name || '' }}
